name: databricks-smoke
on:
  workflow_dispatch:
  push:
    branches: [dev, main]

jobs:
  smoke:
    runs-on: ubuntu-latest

    # ⬇️ Exporta host/token/usuario para TODOS los steps
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DBX_USER: ${{ secrets.DBX_USER }}

    steps:
      - uses: actions/checkout@v4

      # Usa la acción oficial
      - uses: databricks/setup-cli@main  # o fija un tag específico

      # ✅ Ya autenticado por env vars; no llames 'databricks auth env'
      - name: Who am I?
        run: databricks current-user me

      - name: List catalogs
        run: databricks catalogs list

      - name: List workspace root
        run: databricks workspace list /

      - name: Import notebooks to Workspace
        run: |
          TARGET_BASE="/Users/$DBX_USER/proj"
          if [ "${{ github.ref_name }}" = "dev" ]; then
            TARGET="$TARGET_BASE/dev"
          else
            TARGET="$TARGET_BASE/prod"
          fi
          databricks workspace mkdirs "$TARGET"
          databricks workspace import-dir notebooks "$TARGET/notebooks" --overwrite
